export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT ="LOGOUT";


export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//user
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED= "GET_USER_FAILED";
//fillter user

export const GET_USER_FILLTER_SUCCESS = "GET_USER_FILLTER_SUCCESS";
export const GET_USER_FILLTER_FAILED= "GET_USER_FILLTER_FAILED";
// edit user
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILED= "EDIT_USER_FAILED";
// get user by id
export const GET_USER_ID_SUCCESS = "GET_USER_ID_SUCCESS";
export const GET_USER_ID_FAILED = "GET_USER_ID_FAILED";
// duplicate user
export const DUP_USER_ID_SUCCESS = "DUP_USER_ID_SUCCESS";
export const DUP_USER_ID_FAILED = "DUP_USER_ID_FAILED";
// unlock,
export const UNLOCK_USER_ID_SUCCESS = "UNLOCK_USER_ID_SUCCESS";
export const UNLOCK_USER_ID_FAILED = "UNLOCK_USER_ID_FAILED";
//  lock user
export const LOCK_USER_ID_SUCCESS = "LOCK_USER_ID_SUCCESS";
export const LOCK_USER_ID_FAILED = "LOCK_USER_ID_FAILED";